load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

package(default_visibility = ["//visibility:public"])

exports_files(["rules.bzl"])

bzl_library(
    name = "rules_godot",
    srcs = ["rules.bzl"],
)
