load("//rules_godot:rules.bzl", "godot_gdextension_rust")

package(default_visibility = ["//visibility:public"])

godot_gdextension_rust(
    name = "character_rust_gdext",
    srcs = glob(["src/**/*.rs"]),
)
