load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

package(default_visibility = ["//visibility:public"])

exports_files(["godot_rules.bzl"])

bzl_library(
    name = "godot_rules",
    srcs = ["godot_rules.bzl"],
)
