package(default_visibility = ["//visibility:public"])

cc_library(
    name = "character_cpp_gdext",
    srcs = glob(["src/*.cpp"]),
    hdrs = glob(["src/*.h"]),
    deps = ["@godot_cpp//:godot-cpp"],
)
